# Generated by Django 3.1.7 on 2021-03-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210318_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='photo',
            field=models.ImageField(default='img/default.png', upload_to='img/'),
        ),
    ]
