# Generated by Django 3.1.7 on 2021-03-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210318_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='penjual',
        ),
        migrations.RemoveField(
            model_name='penjual',
            name='nama_depan',
        ),
        migrations.AddField(
            model_name='penjual',
            name='nama_dapan',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='barang',
            name='harga_barang',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='penjual',
            name='nama_belakang',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
